// PROJECT_PASS=""
// DATABASE_URL=""
// PORT=3000
// NODE_ENV="development"
// CLIENT_URI="http://localhost:5173/"

// # Get it from google
// GOOGLE_CLIENT_ID=""
// GOOGLE_CLIENT_SECRET=""
// GOOGLE-REDIRECT_URI=""

// JWT_ACCESS_SECRET=""
// JWT_REFRESH_SECRET=""
// JWT_ACCESS_SECRET_EXPIRY="10m"
// JWT_REFRESH_SECRET_EXPIRY="7d"

// MSG91_TEMPLATE_ID=""
// MSG91_SENDER_ID=""
// MSG91_AUTH_KEY=""